---
title: Artwork In Code
author: Ace Mark Acebedo
date: '2018-03-24'
slug: artwork-in-code
categories:
  - R
tags:
  - R Trail
header:
  caption: ''
  image: ''
---
While there is the determined attempt of the technical world - experts,consultants, technical advisers, academic institutions in creating data science courses, offer data science services to monetize and capitalize on the current data science "hype", reading a blog like [Fronkonstin](https://fronkonstin.com) created by Antonio Sánchez Chinchón of Telefonica - featured in a Data Camp course on [phyllotaxiz](https://www.datacamp.com/projects/62?utm_medium=fb%2Cig%2Can%2Cms-all&utm_source=fb_paid&utm_campaign=smartly_ppa&utm_id=5a9dcd6da5ec6c214b2cb7c5), for someone like me who thinks and breathes R, it's just a 'breath of fresh air'.

Looking at the monstrous detail of the visualization in a short amount of [code](https://github.com/aschinchon/mandalas-colored),

```{r, echo=FALSE,message=FALSE,fig.height=5,fig.width=5}
# Load in libraries
library(ggplot2)
library(dplyr)
library(deldir)
library(colourlovers)
library(rlist)

# Parameters
iter=3 # Number of iterations (depth)
points=14 # Number of points
radius=1.14 # Factor of expansion/compression

# Angles of points from center
angles=seq(0, 2*pi*(1-1/points), length.out = points)+pi/2

# Initial center
df=data.frame(x=0, y=0)

# Iterate over centers again and again
for (k in 1:iter)
{
  temp=data.frame()
  for (i in 1:nrow(df))
  {
    data.frame(x=df[i,"x"]+radius^(k-1)*cos(angles), 
               y=df[i,"y"]+radius^(k-1)*sin(angles)) %>% rbind(temp) -> temp
  }
  df=temp
}

# Function to extract id, coordinates and area of each polygon
crea = function(tile) {tile %>% list.match("ptNum|x|y|area") %>% as.data.frame()}

# Generate tesselation, obtain polygons and create a dataframe with results
# This dataframe will be the input of ggplot
df %>% 
  deldir(sort = TRUE)  %>% 
  tile.list() %>% 
  list.filter(sum(bp)==0) %>% 
  list.filter(length(intersect(which(x==0), which(y==0)))==0) %>% 
  lapply(crea) %>% 
  list.rbind() ->  df_polygon

# Pick a random top palette from colourLovers
palette <- sample(clpalettes('top'), 1)[[1]] %>% swatch %>% .[[1]]

# Draw mandala with geom_polygon. Colur depends on area
ggplot(df_polygon, aes(x = x, y = y)) +
  geom_polygon(aes(fill = area, color=area, group = ptNum), 
               show.legend = FALSE, size=0)+
  scale_fill_gradientn(colors=sample(palette, length(palette))) + 
  scale_color_gradientn(colors="gray30") +   
  theme_void()

# Do you like the result? You can save it (change the filename):
#ggsave("my_mandala.png", height=5, width=5, units='in', dpi=600)
```

Just inspires me to keep exploring and doing things in R - this also eclipses my gaze at the python track, from this point on #IuseR -exclusively.

While doing this blog I came across [Docker Hub](https://hub.docker.com)... yet to read up on this, seems filled with some serious neat tech stuff. I just recalled [Flowing Data](https://flowingdata.com) as well, my first source or R amazement with regard to the language's application.





