---
title: LTE Transport Quality
author: Ace Mark Acebedo
date: '2018-02-16'
slug: lte-transport-quality
categories: []
tags:
  - RF Stuff
---
### LTE IPPM Strategic Deployment

**Telcos are in a race** to secure confidence among their subscribers and its not surprising that technical people are put to work to secure the end-to-end subscriber experience measured primarily in terms of speed - or more technically, `the throughput.` 

One peculiar matter for the LTE is its sensitivity to delay - were talking about a base requirement of 10ms which correspondes to the LTE Radio frame. We have highly developed eNodeBs to handle the air interface well enough but there should be an alignment with these quality requirements on the transport interface to the eNodeB. 

So far, it is a challenge for every operator to monitor the quality of the last mile transport link to the eNodeB. Huawei provides a solution for monitoring the transport quality through a proprietary feature IPPM (IP Performance Monitoring Feature). Its been proposed to have the following kpi monitoring thresholds in place:

Interface      | BackJitter    | ForwardJitter | Rtt           | PLR
 ------------- | ------------- | ------------- | ------------- | -----
 S1            | <4ms          | <4ms          | <20ms         | <0.001%
 X2            | <4ms          | <4ms          | <8ms          | <0.001%


Based on actual testing, there is a substantial drop in the subscriber throughput when either one of the above thresholds are breached - an `instantaneous reduction of 90%`!

Most of the eNodeBs that were detected to have issues in terms of the IPPM metrics are those which requires port-shaping (down-time there!) and those still hooked up on microwave transport links.








